// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'get-started',
    {
      type: 'category',
      label: 'Exploits',
      items: [
        'exploits/badrecovery',
        'exploits/sh1mmer',
        'exploits/e-halcyon',
        'exploits/v101',
        'exploits/v101-crosh',
        'exploits/v81',
        'exploits/v81-crosh',
        'exploits/v81-kiosk',
        'exploits/v87',
        'exploits/v87-crosh',
        'exploits/v91',
        'exploits/v91-crosh',
      ],
    },
    'fakemurk',
    'finalizing-setup',
    'what-now',
    {
      type: 'category',
      label: 'Extras',
      items: [
        'extras/murkmod',
        'extras/depthboot',
        'extras/lilac',
        'extras/ltbeef',
        'extras/cedr',
        'extras/useragent-switching'
      ]
    },
    {
      type: 'category',
      label: 'Other',
      items: [
        'other/identify-wp',
        'other/choose-halcyon',
        'other/disable-wp-battery',
        'other/disable-wp-screw',
        'other/disable-wp-switch',
        'other/re-enroll',
      ]
    }
  ],
};

export default sidebars;
